#!/bin/bash

# Development Environment Setup Script for Rabbit Hole
# Sets up complete local development stack with all services

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
DEV_ENV_FILE="$PROJECT_ROOT/.env.dev"
DEV_COMPOSE_FILE="$PROJECT_ROOT/docker-compose.dev.yml"

# Helper functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${PURPLE}[STEP]${NC} $1"
}

print_banner() {
    echo -e "${BLUE}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║                     Rabbit Hole Development                 ║"
    echo "║                    Environment Setup                        ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

check_requirements() {
    log_step "Checking development requirements..."
    
    local failed=0
    
    # Check Docker
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed. Please install Docker Desktop or Docker Engine."
        failed=1
    else
        log_success "Docker found: $(docker --version)"
    fi
    
    # Check Docker Compose
    if ! docker compose version &> /dev/null; then
        log_error "Docker Compose is not available. Please install Docker Compose v2+"
        failed=1
    else
        log_success "Docker Compose found: $(docker compose version --short)"
    fi
    
    # Check Node.js
    if ! command -v node &> /dev/null; then
        log_warning "Node.js not found. Docker will handle this, but local development tools may not work."
    else
        log_success "Node.js found: $(node --version)"
    fi
    
    # Check pnpm
    if ! command -v pnpm &> /dev/null; then
        log_warning "pnpm not found. Installing pnpm globally..."
        npm install -g pnpm@latest
        log_success "pnpm installed: $(pnpm --version)"
    else
        log_success "pnpm found: $(pnpm --version)"
    fi
    
    # Check available ports
    local ports=(3000 7474 7687 8000 8001 9000 9001 6379 9090 3001 8081)
    local occupied_ports=()
    
    for port in "${ports[@]}"; do
        if lsof -Pi :$port -sTCP:LISTEN -t >/dev/null 2>&1; then
            occupied_ports+=($port)
        fi
    done
    
    if [ ${#occupied_ports[@]} -gt 0 ]; then
        log_warning "Some ports are already occupied: ${occupied_ports[*]}"
        log_warning "You may need to stop existing services or change port mappings"
    else
        log_success "All required ports are available"
    fi
    
    if [ $failed -eq 1 ]; then
        log_error "Requirements check failed. Please install missing dependencies."
        exit 1
    fi
    
    log_success "All requirements met"
}

setup_environment() {
    log_step "Setting up development environment configuration..."
    
    # Create development environment file if it doesn't exist
    if [ ! -f "$DEV_ENV_FILE" ]; then
        log_info "Creating development environment file..."
        
        cat > "$DEV_ENV_FILE" << 'EOF'
# Development Environment Configuration
# Generated by dev-setup.sh

# === API KEYS (Optional for development) ===
# Add your API keys here for full functionality
OPENAI_API_KEY=
GEMINI_API_KEY=

# === DEVELOPMENT SETTINGS ===
NODE_ENV=development
DEBUG=rabbit-hole:*
LOG_LEVEL=debug

# === DATABASE SETTINGS ===
NEO4J_URI=bolt://localhost:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=evidencegraph2024

REDIS_URL=redis://localhost:6379

MINIO_ENDPOINT=localhost:9000
MINIO_ACCESS_KEY=minio
MINIO_SECRET_KEY=minio123

# === SERVICE URLS ===
NEXT_PUBLIC_API_URL=http://localhost:3000/api
LANGEXTRACT_URL=http://localhost:8000

# === DEVELOPMENT FLAGS ===
DISABLE_TELEMETRY=true
ENABLE_DEBUGGING=true
HOT_RELOAD=true
EOF
        
        log_success "Created development environment file: $DEV_ENV_FILE"
        log_warning "Please add your API keys to $DEV_ENV_FILE for full functionality"
    else
        log_success "Development environment file already exists"
    fi
}

setup_directories() {
    log_step "Setting up development directories..."
    
    # Create necessary directories
    mkdir -p "$PROJECT_ROOT/monitoring"
    mkdir -p "$PROJECT_ROOT/test-data"
    mkdir -p "$PROJECT_ROOT/logs/dev"
    
    # Create Prometheus development config if it doesn't exist
    if [ ! -f "$PROJECT_ROOT/monitoring/prometheus.dev.yml" ]; then
        cat > "$PROJECT_ROOT/monitoring/prometheus.dev.yml" << 'EOF'
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'development'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Next.js application
  - job_name: 'nextjs-ui'
    static_configs:
      - targets: ['nextjs-ui:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # Neo4j (if metrics are available)
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j-dev:2004']
    scrape_interval: 30s

  # LangExtract service
  - job_name: 'langextract'
    static_configs:
      - targets: ['langextract-dev:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
EOF
        log_success "Created Prometheus development configuration"
    fi
    
    log_success "Development directories set up"
}

build_development_images() {
    log_step "Building development Docker images..."
    
    cd "$PROJECT_ROOT"
    
    # Build Next.js development image
    log_info "Building Next.js development image..."
    
    # Create development Dockerfile if it doesn't exist
    if [ ! -f "$PROJECT_ROOT/Dockerfile.nextjs" ]; then
        log_error "Dockerfile.nextjs not found. Please ensure it exists with a development target."
        exit 1
    fi
    
    # Add development target to Dockerfile.nextjs if not present
    if ! grep -q "FROM.*AS development" "$PROJECT_ROOT/Dockerfile.nextjs"; then
        log_info "Adding development target to Dockerfile.nextjs..."
        
        # Create temporary Dockerfile with development target
        cat > "$PROJECT_ROOT/Dockerfile.dev.tmp" << 'EOF'
# Development stage - add this to your Dockerfile.nextjs after the base stage
FROM base AS development
WORKDIR /app

# Copy package files
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages/types/package.json ./packages/types/
COPY packages/utils/package.json ./packages/utils/
COPY packages/prompts/package.json ./packages/prompts/
COPY packages/proto-llm-tools/package.json ./packages/proto-llm-tools/

# Install pnpm and dependencies
RUN npm install -g pnpm@latest
RUN pnpm install --frozen-lockfile

# Copy source code
COPY . .

# Expose development ports
EXPOSE 3000 9229

# Start development server
CMD ["pnpm", "dev"]
EOF
        
        # Add development stage to existing Dockerfile
        cp "$PROJECT_ROOT/Dockerfile.nextjs" "$PROJECT_ROOT/Dockerfile.nextjs.bak"
        
        # Insert development stage after the base stage
        awk '/FROM.*AS base/ {print; getline; print; print ""; print "# Development stage"; while ((getline line < "'"$PROJECT_ROOT"'/Dockerfile.dev.tmp") > 0) print line; close("'"$PROJECT_ROOT"'/Dockerfile.dev.tmp"); print ""} !/FROM.*AS base/ {print}' "$PROJECT_ROOT/Dockerfile.nextjs.bak" > "$PROJECT_ROOT/Dockerfile.nextjs"
        
        rm "$PROJECT_ROOT/Dockerfile.dev.tmp" "$PROJECT_ROOT/Dockerfile.nextjs.bak"
        
        log_success "Added development target to Dockerfile.nextjs"
    fi
    
    # Build development images
    docker compose -f "$DEV_COMPOSE_FILE" build --no-cache
    
    log_success "Development images built successfully"
}

start_development_stack() {
    log_step "Starting development stack..."
    
    cd "$PROJECT_ROOT"
    
    # Start services with Docker Compose
    docker compose -f "$DEV_COMPOSE_FILE" up -d
    
    log_info "Waiting for services to initialize..."
    sleep 10
    
    # Wait for services to be healthy
    local max_attempts=30
    local attempt=1
    
    while [ $attempt -le $max_attempts ]; do
        local healthy_services=0
        local total_services=0
        
        # Check each service health
        for service in neo4j-dev redis-dev minio-dev langextract-dev; do
            total_services=$((total_services + 1))
            if docker compose -f "$DEV_COMPOSE_FILE" ps "$service" | grep -q "healthy"; then
                healthy_services=$((healthy_services + 1))
            fi
        done
        
        if [ $healthy_services -eq $total_services ]; then
            log_success "All services are healthy and ready"
            break
        fi
        
        log_info "Waiting for services... ($healthy_services/$total_services healthy) - Attempt $attempt/$max_attempts"
        sleep 5
        attempt=$((attempt + 1))
    done
    
    if [ $attempt -gt $max_attempts ]; then
        log_warning "Some services may not be fully ready. Check logs if needed."
    fi
    
    log_success "Development stack started successfully"
}

seed_test_data() {
    log_step "Seeding comprehensive test data from existing bundles..."
    
    # Wait for Neo4j to be fully ready
    sleep 10
    
    # Wait for Next.js API to be ready
    local max_attempts=30
    local attempt=1
    
    while [ $attempt -le $max_attempts ]; do
        if curl -f -s http://localhost:3000/api/health > /dev/null 2>&1; then
            log_success "Next.js API is ready for data ingestion"
            break
        fi
        log_info "Waiting for Next.js API... (attempt $attempt/$max_attempts)"
        sleep 3
        attempt=$((attempt + 1))
    done
    
    # Check if test data already exists
    local node_count=$(docker compose -f "$DEV_COMPOSE_FILE" exec -T neo4j-dev cypher-shell -u neo4j -p evidencegraph2024 "MATCH (n) RETURN count(n) as count" 2>/dev/null | tail -n 1 | cut -d'|' -f2 | tr -d ' ' | tr -d '"')
    
    if [ "$node_count" = "0" ] || [ -z "$node_count" ]; then
        log_info "Loading comprehensive test data from 15+ entity bundles..."
        
        # First run database setup to create schema
        log_info "Setting up Rabbit Hole schema..."
        cd "$PROJECT_ROOT"
        pnpm run db:dev 2>/dev/null || log_warning "Schema setup may have had issues, continuing with data ingestion"
        
        # Load all test data files via bulk import API
        local loaded_files=0
        local failed_files=0
        
        for test_file in "$PROJECT_ROOT/test-data"/*.json; do
            if [ -f "$test_file" ]; then
                local filename=$(basename "$test_file")
                log_info "Loading $filename..."
                
                # Use the bulk import API to load each file
                if curl -X POST "http://localhost:3000/api/ingest-bundle" \
                   -H "Content-Type: application/json" \
                   -d @"$test_file" \
                   -w "%{http_code}" -o /dev/null -s | grep -q "200"; then
                    loaded_files=$((loaded_files + 1))
                    log_success "✓ Loaded $filename"
                else
                    failed_files=$((failed_files + 1))
                    log_warning "✗ Failed to load $filename"
                fi
            fi
        done
        
        log_success "Test data ingestion complete: $loaded_files files loaded, $failed_files failed"
        
        # Verify data was loaded
        sleep 2
        local final_count=$(docker compose -f "$DEV_COMPOSE_FILE" exec -T neo4j-dev cypher-shell -u neo4j -p evidencegraph2024 "MATCH (n) RETURN count(n) as count" 2>/dev/null | tail -n 1 | cut -d'|' -f2 | tr -d ' ' | tr -d '"')
        
        if [ "$final_count" -gt "0" ]; then
            log_success "Database now contains $final_count entities"
            
            # Run community detection for complete setup
            log_info "Computing community detection for clustering..."
            pnpm run db:communities 2>/dev/null || log_warning "Community detection setup may have had issues"
        else
            log_warning "Data verification failed - database may be empty"
        fi
        
    else
        log_success "Test data already exists ($node_count entities in database)"
    fi
}

verify_services() {
    log_step "Verifying service connectivity..."
    
    local failed_services=()
    
    # Check Next.js (may take time to start)
    log_info "Checking Next.js UI..."
    local attempt=1
    local max_attempts=20
    while [ $attempt -le $max_attempts ]; do
        if curl -f -s http://localhost:3000/api/health > /dev/null 2>&1; then
            log_success "✓ Next.js UI: http://localhost:3000"
            break
        fi
        if [ $attempt -eq $max_attempts ]; then
            failed_services+=("Next.js UI")
            log_error "✗ Next.js UI: http://localhost:3000 (not responding)"
        fi
        sleep 3
        attempt=$((attempt + 1))
    done
    
    # Check Neo4j
    if docker compose -f "$DEV_COMPOSE_FILE" exec -T neo4j-dev cypher-shell -u neo4j -p evidencegraph2024 "RETURN 1" > /dev/null 2>&1; then
        log_success "✓ Neo4j Database: http://localhost:7474"
    else
        failed_services+=("Neo4j")
        log_error "✗ Neo4j Database: http://localhost:7474"
    fi
    
    # Check Redis
    if docker compose -f "$DEV_COMPOSE_FILE" exec -T redis-dev redis-cli ping > /dev/null 2>&1; then
        log_success "✓ Redis Cache: localhost:6379"
    else
        failed_services+=("Redis")
        log_error "✗ Redis Cache: localhost:6379"
    fi
    
    # Check MinIO
    if curl -f -s http://localhost:9000/minio/health/live > /dev/null 2>&1; then
        log_success "✓ MinIO Storage: http://localhost:9001 (minio/minio123)"
    else
        failed_services+=("MinIO")
        log_error "✗ MinIO Storage: http://localhost:9001"
    fi
    
    # Check LangExtract
    if curl -f -s http://localhost:8000/health > /dev/null 2>&1; then
        log_success "✓ LangExtract API: http://localhost:8000/docs"
    else
        failed_services+=("LangExtract")
        log_error "✗ LangExtract API: http://localhost:8000"
    fi
    
    # Check additional services
    if curl -f -s http://localhost:9090/-/ready > /dev/null 2>&1; then
        log_success "✓ Prometheus Monitoring: http://localhost:9090"
    else
        log_warning "Prometheus not ready (this is optional)"
    fi
    
    if curl -f -s http://localhost:3001/api/health > /dev/null 2>&1; then
        log_success "✓ Grafana Dashboard: http://localhost:3001 (admin/admin)"
    else
        log_warning "Grafana not ready (this is optional)"
    fi
    
    if curl -f -s http://localhost:8081 > /dev/null 2>&1; then
        log_success "✓ Redis Commander: http://localhost:8081"
    else
        log_warning "Redis Commander not ready (this is optional)"
    fi
    
    if [ ${#failed_services[@]} -eq 0 ]; then
        log_success "All core services are running correctly"
        return 0
    else
        log_error "Failed services: ${failed_services[*]}"
        return 1
    fi
}

show_development_info() {
    echo ""
    log_success "=== DEVELOPMENT ENVIRONMENT READY ==="
    echo ""
    echo -e "${GREEN}🚀 Core Services:${NC}"
    echo "   • Next.js UI:        http://localhost:3000"
    echo "   • Atlas Interface:   http://localhost:3000/atlas"
    echo "   • Neo4j Browser:     http://localhost:7474 (neo4j/evidencegraph2024)" 
    echo "   • LangExtract API:   http://localhost:8000/docs"
    echo "   • MinIO Console:     http://localhost:9001 (minio/minio123)"
    echo ""
    echo -e "${BLUE}📊 Monitoring Tools:${NC}"
    echo "   • Prometheus:        http://localhost:9090"
    echo "   • Grafana:          http://localhost:3001 (admin/admin)"
    echo "   • Redis Commander:   http://localhost:8081"
    echo ""
    echo -e "${YELLOW}🛠️ Development Commands:${NC}"
    echo "   • View logs:         docker compose -f docker-compose.dev.yml logs -f"
    echo "   • Restart service:   docker compose -f docker-compose.dev.yml restart [service-name]"
    echo "   • Stop all:          docker compose -f docker-compose.dev.yml down"
    echo "   • Rebuild:           docker compose -f docker-compose.dev.yml up --build -d"
    echo ""
    echo -e "${PURPLE}📝 Test Data Available:${NC}"
    echo "   • 15+ entity bundles loaded (Trump, Biden, Musk, Jones, etc.)"
    echo "   • Complete evidence provenance with source attribution"
    echo "   • Family relationships, political networks, business connections"
    echo "   • Speech acts, hostile content, timeline data"
    echo "   • Community detection computed for network clustering"
    echo ""
    echo -e "${PURPLE}📝 Next Steps:${NC}"
    echo "   1. Add your API keys to .env.dev for full AI functionality"
    echo "   2. Explore the Atlas: http://localhost:3000/atlas"
    echo "   3. Try AI research: Right-click any entity in Atlas"
    echo "   4. Check entity timelines: Click any node → Timeline tab"
    echo "   5. Start developing with hot reloading enabled"
    echo ""
    log_warning "API Keys: Add OPENAI_API_KEY and GEMINI_API_KEY to .env.dev for AI features"
    echo ""
}

cleanup_on_failure() {
    log_error "Setup failed. Cleaning up..."
    docker compose -f "$DEV_COMPOSE_FILE" down --remove-orphans
    exit 1
}

# Main setup flow
main() {
    print_banner
    
    # Set up error handling
    trap cleanup_on_failure ERR
    
    log_info "Starting development environment setup..."
    
    check_requirements
    setup_environment
    setup_directories
    build_development_images
    start_development_stack
    seed_test_data
    
    if verify_services; then
        show_development_info
        log_success "🎉 Development environment setup completed successfully!"
        
        # Optional: Open browser to main application
        if command -v open &> /dev/null; then
            log_info "Opening application in browser..."
            open http://localhost:3000
        elif command -v xdg-open &> /dev/null; then
            log_info "Opening application in browser..."
            xdg-open http://localhost:3000
        fi
        
    else
        log_error "Some services failed verification. Check logs and try restarting individual services."
        exit 1
    fi
}

# Run with error handling
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
