/**
 * Domain Scanner - Auto-discovery and TypeScript Generation (RAB-16)
 *
 * Discovers all domain.config.json files in custom-domains/
 * Validates them using RAB-14 schema
 * Generates TypeScript domain configs with Zod schemas
 * Generates registry for automatic domain registration
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { relative } from "path";

import { glob } from "glob";

import {
  validateJSONDomain,
  convertJSONDomainToZod,
  type JSONDomainConfig,
} from "@proto/types";

interface ScannedDomain {
  path: string;
  relativePath: string;
  name: string;
  sanitizedName: string;
  config: unknown;
  validatedConfig: JSONDomainConfig;
}

/**
 * Sanitize domain name for use as JavaScript identifier
 */
function sanitizeDomainName(name: string): string {
  // Replace non-alphanumeric chars with underscores
  let sanitized = name.replace(/[^a-zA-Z0-9_]/g, "_");

  // Ensure doesn't start with digit
  if (/^\d/.test(sanitized)) {
    sanitized = `_${sanitized}`;
  }

  return sanitized;
}

/**
 * Generate TypeScript domain config file with Zod schemas
 */
async function generateDomainConfigFile(domain: ScannedDomain): Promise<void> {
  const outputDir = ".generated/custom-domains";
  const outputFile = `${outputDir}/${domain.name}.ts`;
  const jsonDomain = domain.validatedConfig;

  // Ensure output directory exists
  mkdirSync(outputDir, { recursive: true });

  // Convert JSON to Zod schemas
  const { entities, uidPrefixes, validators } =
    convertJSONDomainToZod(jsonDomain);

  // Generate entity schemas
  const entitySchemas: string[] = [];
  Object.entries(jsonDomain.entities).forEach(([entityType, entityDef]) => {
    const safeEntityId = sanitizeDomainName(entityType);
    const schemaName = `${safeEntityId}Schema`;
    const properties = entityDef.properties || {};

    const propsSchemaLines: string[] = [];
    Object.entries(properties).forEach(([propName, propDef]) => {
      let zodType = "";
      switch (propDef.type) {
        case "string":
          zodType = "z.string()";
          if (propDef.minLength) zodType += `.min(${propDef.minLength})`;
          if (propDef.maxLength) zodType += `.max(${propDef.maxLength})`;
          if (propDef.pattern) {
            zodType += `.regex(new RegExp(${JSON.stringify(propDef.pattern)}))`;
          }
          break;
        case "number":
          zodType = "z.number()";
          if (propDef.integer) zodType += ".int()";
          if (propDef.min !== undefined) zodType += `.min(${propDef.min})`;
          if (propDef.max !== undefined) zodType += `.max(${propDef.max})`;
          break;
        case "boolean":
          zodType = "z.boolean()";
          break;
        case "date":
          zodType =
            propDef.format === "ISO8601"
              ? "z.string().datetime()"
              : "z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/)";
          break;
        case "array":
          if (typeof propDef.items === "string") {
            const itemType =
              propDef.items === "string"
                ? "z.string()"
                : propDef.items === "number"
                  ? "z.number()"
                  : "z.boolean()";
            zodType = `z.array(${itemType})`;
          } else {
            const enumValues = JSON.stringify(propDef.items.enum);
            zodType = `z.array(z.enum(${enumValues} as const))`;
          }
          break;
        case "object": {
          const valueType =
            propDef.valueType === "string"
              ? "z.string()"
              : propDef.valueType === "number"
                ? "z.number()"
                : "z.unknown()";
          zodType = `z.record(z.string(), ${valueType})`;
          break;
        }
        case "enum": {
          const values = JSON.stringify(propDef.values);
          zodType = `z.enum(${values} as const)`;
          break;
        }
      }

      if (!propDef.required) {
        zodType += ".optional()";
      }

      propsSchemaLines.push(`    ${JSON.stringify(propName)}: ${zodType},`);
    });

    const baseSchema = `z.object({
  uid: z.string().min(1),
  type: z.literal(${JSON.stringify(entityType)}),
  name: z.string().min(1),
  aliases: z.array(z.string()).optional(),
  tags: z.array(z.string()).optional(),
  properties: z.object({
${propsSchemaLines.join("\n")}
  }).optional(),
})`;

    entitySchemas.push(`const ${schemaName} = ${baseSchema};`);
  });

  // Generate validators
  const validatorEntries = Object.entries(uidPrefixes)
    .map(
      ([entityType, prefix]) =>
        `  "${prefix}": (uid: string) => uid.startsWith("${prefix}:")`
    )
    .join(",\n");

  const content = `/**
 * Auto-generated Domain Config: ${jsonDomain.displayName}
 * 
 * DO NOT EDIT - This file is automatically generated by scripts/scan-domains.ts
 * 
 * Source: ${domain.relativePath}
 */

import { z } from 'zod';

import type { DomainConfig } from '@proto/types';

// Entity Schemas
${entitySchemas.join("\n\n")}

// Domain Configuration
export const ${domain.sanitizedName}DomainConfig: DomainConfig = {
  name: ${JSON.stringify(jsonDomain.name)},
  displayName: ${JSON.stringify(jsonDomain.displayName)},
  description: ${JSON.stringify(jsonDomain.description)},
  category: "custom",
  
  entities: {
${Object.keys(jsonDomain.entities)
  .map(
    (type) =>
      `    ${JSON.stringify(type)}: ${sanitizeDomainName(type)}Schema as z.ZodTypeAny`
  )
  .join(",\n")}
  },
  
  uidPrefixes: {
${Object.entries(uidPrefixes)
  .map(
    ([type, prefix]) => `    ${JSON.stringify(type)}: ${JSON.stringify(prefix)}`
  )
  .join(",\n")}
  },
  
  validators: {
${validatorEntries}
  },
  
  ui: ${JSON.stringify(jsonDomain.ui, null, 2)},
  
  ${jsonDomain.relationships ? `relationships: ${JSON.stringify(jsonDomain.relationships)},` : ""}
  ${jsonDomain.extendsFrom ? `extendsFrom: ${JSON.stringify(jsonDomain.extendsFrom)},` : ""}
  ${jsonDomain.version ? `version: ${JSON.stringify(jsonDomain.version)},` : ""}
  ${jsonDomain.author ? `author: ${JSON.stringify(jsonDomain.author)},` : ""}
  ${jsonDomain.tags ? `tags: ${JSON.stringify(jsonDomain.tags)},` : ""}
};
`;

  writeFileSync(outputFile, content, "utf-8");
  console.log(`   ├─ Generated: ${domain.name}.ts`);
}

async function scanDomains(): Promise<void> {
  console.log("🔍 Scanning for domain configurations...\n");

  // Find all domain.config.json files
  const domainFiles = await glob("custom-domains/**/domain.config.json", {
    cwd: process.cwd(),
    absolute: false,
    ignore: ["**/__*__/**", "**/__*__"],
  });

  if (domainFiles.length === 0) {
    console.log("⚠️  No domain configurations found in custom-domains/");
    await generateEmptyRegistry();
    return;
  }

  // Run validation first if --validate flag is present
  const shouldValidate = process.argv.includes("--validate");
  if (shouldValidate) {
    console.log("🔍 Running validation checks...\n");
    // Note: Full validation is in validate-domains.ts
    // Scanner only does basic schema validation
  }

  const domains: ScannedDomain[] = [];
  const errors: Array<{ file: string; error: string }> = [];

  // Validate each domain
  for (const file of domainFiles) {
    try {
      const json = JSON.parse(readFileSync(file, "utf-8"));

      // Validate with RAB-14 schema
      const validation = validateJSONDomain(json);

      if (!validation.success) {
        errors.push({
          file,
          error: validation.error.message,
        });
        continue;
      }

      domains.push({
        path: file,
        relativePath: relative(process.cwd(), file),
        name: validation.data.name,
        sanitizedName: sanitizeDomainName(validation.data.name),
        config: json,
        validatedConfig: validation.data,
      });

      console.log(`✅ ${file}`);
    } catch (error) {
      errors.push({
        file,
        error: error instanceof Error ? error.message : String(error),
      });
    }
  }

  console.log(`\n📊 Found ${domains.length} valid domain(s)\n`);

  // Report errors
  if (errors.length > 0) {
    console.error(`\n❌ ${errors.length} domain(s) failed validation:\n`);
    errors.forEach(({ file, error }) => {
      console.error(`  ${file}:`);
      console.error(`    ${error}\n`);
    });
    process.exit(1);
  }

  console.log("🔨 Generating TypeScript domain configs...\n");

  // Generate individual domain config files
  for (const domain of domains) {
    await generateDomainConfigFile(domain);
  }

  console.log("");

  // Sort domains alphabetically by name to satisfy eslint import/order
  domains.sort((a, b) => a.name.localeCompare(b.name, "en-US"));

  // Update domain registry
  await generateDomainRegistry(domains);

  // Note: Not generating packages/types/src/custom-domains/index.ts anymore
  // The .generated files are runtime-only and consumed directly by the app
  // to avoid TypeScript composite project conflicts with rootDir settings
}

async function generateDomainRegistry(domains: ScannedDomain[]): Promise<void> {
  const outputDir = ".generated/custom-domains";
  const outputFile = `${outputDir}/registry.ts`;

  // Create output directory
  mkdirSync(outputDir, { recursive: true });

  // Generate TypeScript imports
  const imports = domains
    .map((d) => `import { ${d.sanitizedName}DomainConfig } from './${d.name}';`)
    .join("\n");

  const registrations = domains
    .map((d) => `  domainRegistry.register(${d.sanitizedName}DomainConfig);`)
    .join("\n");

  const content = `/**
 * Auto-generated Custom Domain Registry
 * 
 * DO NOT EDIT - This file is automatically generated by scripts/scan-domains.ts
 * 
 * Domains: ${domains.length}
 */

import { domainRegistry } from '@proto/types';

${imports}

/**
 * Register all custom domains
 * Call this during application initialization
 */
export function registerCustomDomains(): void {
  console.log('📦 Registering ${domains.length} custom domain(s)...');
  
${registrations}
  
  console.log('✅ Custom domains registered');
}

/**
 * List of discovered custom domain names
 */
export const customDomainNames = [
${domains.map((d) => `  '${d.name}',`).join("\n")}
];
`;

  writeFileSync(outputFile, content, "utf-8");
  console.log(`✅ Generated: registry.ts\n`);
}

async function generateEmptyRegistry(): Promise<void> {
  const outputDir = ".generated/custom-domains";
  const outputFile = `${outputDir}/registry.ts`;

  mkdirSync(outputDir, { recursive: true });

  const content = `/**
 * Auto-generated Custom Domain Registry
 * 
 * DO NOT EDIT - This file is automatically generated by scripts/scan-domains.ts
 * 
 * Domains: 0
 */

/**
 * Register all custom domains
 * No custom domains found
 */
export function registerCustomDomains(): void {
  // No custom domains to register
}

/**
 * List of discovered custom domain names
 */
export const customDomainNames: string[] = [];
`;

  writeFileSync(outputFile, content, "utf-8");
  console.log(`✅ Generated empty registry: ${outputFile}\n`);
}

/**
 * Generate exports for @proto/types package
 * Allows custom domains to be bundled with the types package
 */
async function generateTypesPackageExports(
  domains: ScannedDomain[]
): Promise<void> {
  const outputDir = "packages/types/src/custom-domains";
  const outputFile = `${outputDir}/index.ts`;

  mkdirSync(outputDir, { recursive: true });

  if (domains.length === 0) {
    // Generate empty exports
    const content = `/**
 * Auto-generated Custom Domain Exports
 * 
 * DO NOT EDIT - This file is automatically generated by scripts/scan-domains.ts
 * 
 * Generated: ${new Date().toISOString()}
 * Domains: 0
 */

// No custom domains to export
`;
    writeFileSync(outputFile, content, "utf-8");
    console.log(`✅ Generated empty @proto/types exports\n`);
    return;
  }

  // Calculate relative path from output directory to .generated
  const generatedDir = ".generated/custom-domains";
  const relativePath = relative(outputDir, generatedDir);

  // Generate re-exports
  const imports = domains
    .map(
      (d) =>
        `export { ${d.sanitizedName}DomainConfig } from "${relativePath}/${d.name}";`
    )
    .join("\n");

  const content = `/**
 * Auto-generated Custom Domain Exports
 * 
 * DO NOT EDIT - This file is automatically generated by scripts/scan-domains.ts
 * 
 * Domains: ${domains.length}
 * 
 * These exports allow custom domains to be bundled with @proto/types,
 * making them available in all execution contexts (server, client, API routes).
 */

${imports}

/**
 * Array of all custom domain configs for batch registration
 */
import { domainRegistry } from "../domain-system/domain-registry";

export const allCustomDomainConfigs = [
${domains.map((d) => `  ${d.sanitizedName}DomainConfig,`).join("\n")}
];

/**
 * Auto-register custom domains on import (client-side)
 * Server-side registration happens via instrumentation.ts
 */
if (typeof window !== "undefined") {
  allCustomDomainConfigs.forEach((config) => {
    domainRegistry.registerIfNeeded(config);
  });
  console.log(\`✅ [Client] Registered \${allCustomDomainConfigs.length} custom domain(s) from @proto/types\`);
}
`;

  writeFileSync(outputFile, content, "utf-8");
  console.log(`✅ Generated @proto/types custom-domains exports\n`);
}

// Run scanner
scanDomains().catch((error) => {
  console.error("❌ Domain scanning failed:", error);
  process.exit(1);
});
